AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app
  
  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: go1.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        PARAM1: VALUE

Resources:

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod


  PostTaskLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/aws/post-lambda
      Handler: main
      Tracing: Active
      Events:
        CreateBook:
          Type: Api
          TracingEnabled: true
          Properties:
            Method: post
            Path: /task
            RestApiId:
              Ref: ApiGatewayApi
              
  GetTasksLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/aws/get-lambda
      Handler: main
      Tracing: Active
      Events:
        CreateBook: # 6
          Type: Api
          TracingEnabled: true
          Properties:
            Method: get
            Path: /task
            RestApiId:
              Ref: ApiGatewayApi

Outputs:
  GetTasksLambdaArn:
    Export:
      Name: GetTasksLambdaArn
    Value:
      Fn::GetAtt:
        - GetTasksLambda
        - Arn
  PostTasksLambdaArn:
    Export:
      Name: PostTasksLambdaArn
    Value:
      Fn::GetAtt:
        - PostTaskLambda
        - Arn